# Generated by Django 4.1.6 on 2023-02-10 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('debit', models.BooleanField(default=False)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
